<?php echo $this->doctype(); ?>
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
		<title>Default Module</title>
	</head>
	
	<body>
		<header>
			<ul>
				<li>Home</li>
				<li>SignUp/SignIn</li>
			</ul>
		</header>
		<div id="container">
			<?php echo $this->layout()->content; ?>
		</div>
		<footer>
			copyright 2016
		</footer>
	</body>

</html>